# Generated by Django 4.2.5 on 2023-09-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('phonenumber', models.CharField(max_length=13)),
                ('summery', models.CharField(max_length=500)),
                ('approval_chance', models.IntegerField()),
            ],
        ),
    ]
