# Generated by Django 4.2.5 on 2023-09-22 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('constructionapp', '0002_visitingreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitingreport',
            name='date_and_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='visitingreport',
            name='usr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
