# Generated by Django 4.1.3 on 2023-09-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructionapp', '0003_visitingreport_date_and_time_visitingreport_usr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitingreport',
            name='date_and_time',
        ),
        migrations.AddField(
            model_name='visitingreport',
            name='visited_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='visitingreport',
            name='visited_time',
            field=models.TimeField(null=True),
        ),
    ]
